name: 'my_DBT'
version: '1.0.0'
config-version: 2

profile: 'my_DBT'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  myproject1:
    +materialized: view
    +persist_docs: false

  myproject2:
    example:
      +materialized: table
      +unique_key: id
      +tags: ['d', 'f']
